
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;

public class AppIntegTest {
    @Test
    public void testAppHasAGreeting() {
        // do something
    }
}
